### ISSUE TITLE
Actions in environment, option external link is broken

### ISSUE THREAD

**Issue by dameert** [ems-project/EMSCoreBundle#12]
This link is working (search of a content type):
![image](https://user-images.githubusercontent.com/1359953/28308609-08a65cc6-6ba7-11e7-8980-92c2458b666a.png)

While this one is not (revision):
![image](https://user-images.githubusercontent.com/1359953/28308661-31abd51a-6ba7-11e7-8ac8-b0ba254d364b.png)

I am using translation tabs, whom do not exist in elasticsearch. But it looks like the non working part is seeing these fields (this object._source.slug_fr will not work because it expects object._source.translations.slug_fr)

**Comment by dameert** [comment]
`{{environment.baseUrl}}/fr/{{object._source.slug_fr}}/{{object._source.sections_fr[0].slug_fr}}`

**Comment by ems-project** [comment]
The data with the virtual fields was given to twig instead of the raw data: Commit  43aa38b2bf5bbf5f48f4eeead47ca35d93ca0727

Note that from this commit, if the generated link is empty the link is disabled in the environment's dropdown menu:
{% if object._source.slug_fr is defined %}{{environment.baseUrl}}/fr/{{object._source.slug_fr}}/{{object._source.slug_fr}}{% endif %}
